server:
  port: 8002

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/playlet_manage?useUnicode=true&characterEncoding=utf-8&serveTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: netcare
    password: netcare
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

Logging:
  level:
    com.rabbiter: info

