
POST http://localhost:8002/api/playlet/save
Content-Type: application/json

{
  "distributor_id": "1814524549803018",
  "playlet_id": "7477466360931418651"
}

###

POST http://localhost:8002/api/jlaccount/getAccessToken
Content-Type: application/json

{
  "appid": "1830365792890956",
  "authcode": "c257b0baef52643470101811f1e9ba9f9fc6c3e4",
  "secret": "d89f8cae68457fff4b954ffb31c633ab9b794f20"
}

###

POST http://localhost:8002/api/jlaccount/saveJlaccount
Content-Type: application/json

{
"account": "htduanju06@163.com",
"authcode": "d1cd791912df8d1b87aa20af544814afba45d5ba"
}

###

POST http://localhost:8002/api/jlaccount/refreshToken
Content-Type: application/json

{
  "appid": "1830365792890956",
  "refreshtoken": "9638f8e67b46db7cb9613cfc942f4747400329fa",
  "secret": "d89f8cae68457fff4b954ffb31c633ab9b794f20"
}

###


POST http://localhost:8002/api/jlaccount/getVideo
Content-Type: application/json

{
  "access_token": "251ed0f011052878aea268bfbd3ca19818e5dfa1",
  "advertiser_id" : "1830369387050058"
}

###

POST http://localhost:8002/api/jlaccount/getImage
Content-Type: application/json

{
  "access_token": "6a144cfbbac2cb1afce126ee4d8e74920cb4f279",
  "advertiser_id" : "1816784868360331"
}

###

POST http://localhost:8002/api/jlaccount/getInfo
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8"
}

###

POST http://localhost:8002/api/jlaccount/getCarousel
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468342951300"
}

###

POST http://localhost:8002/api/jlaccount/getCarouselAd
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468342951300",
  "carousel_ids" : "7494621992639266855",
  "carousel_ids1" : "7494622024477163532"
}

###

POST http://localhost:8002/api/jlaccount/getAwemeAuth
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468665720323"
}

###

POST http://localhost:8002/api/jlaccount/getPromotion
Content-Type: application/json

{
  "access_token": "b51a7ae199ddf51a92c78c06e83da74515508297",
  "advertiser_id" : "1828375816639556"
}

###

POST http://localhost:8002/api/jlaccount/video_cover
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468665720323",
  "video_id": "v03033g10000d00rtffog65h88vh0ljg"
}

###

POST http://localhost:8002/api/jlaccount/getMicroApp_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/getAvailables_test
Content-Type: application/json

{
  "access_token": "1177cc7ac70dd6bf713437aea9531504fd4948b3",
  "advertiser_id" : "1827709880869188"
}

###

POST http://localhost:8002/api/jlaccount/getDpaDetail_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830435021693191"
}

###

POST http://localhost:8002/api/jlaccount/getVideoAweme
Content-Type: application/json

{
  "access_token": "d3ba4dba4bece19be1b01bea2ddeb94a6082d8f1",
  "advertiser_id" : "1830435049631817"
}

###

POST http://localhost:8002/api/jlaccount/uploadTask
Content-Type: application/json

{
  "access_token": "d3ba4dba4bece19be1b01bea2ddeb94a6082d8f1",
  "advertiser_id" : "1830435049631817"
}

###

POST http://localhost:8002/api/jlaccount/createSite
Content-Type: application/json

{
  "access_token": "6a144cfbbac2cb1afce126ee4d8e74920cb4f279",
  "advertiser_id" : "1816784868360331"
}

###

POST http://localhost:8002/api/jlaccount/updateSiteStatus
Content-Type: application/json

{
  "access_token": "6a144cfbbac2cb1afce126ee4d8e74920cb4f279",
  "advertiser_id" : "1816784868360331"
}

###

POST http://localhost:8002/api/jlaccount/getSiteStatus
Content-Type: application/json

{
  "access_token": "136bc18daf1a8b31b1fb790b206d8e203ef41725",
  "advertiser_id" : "1816783953792139",
  "site_id" : "7509926613904375862"
}

###

POST http://localhost:8002/api/jlaccount/getWechatAppletStatus
Content-Type: application/json

{
  "access_token": "136bc18daf1a8b31b1fb790b206d8e203ef41725",
  "advertiser_id" : "1816783953792139"
}

###

POST http://localhost:8002/api/jlaccount/createWechatApplet_test
Content-Type: application/json

{
  "access_token": "ed3dd24419f0fb97b9f6f3990d67f6f110bb5a82",
  "advertiser_id" : "1816784868360331"
}

###

POST http://localhost:8002/api/jlaccount/getProject_test
Content-Type: application/json

{
  "access_token": "ec23e0a4fc167c861bffdcd8eeb4f066e982fc11",
  "advertiser_id" : "1832622207797384"
}

###

POST http://localhost:8002/api/jlaccount/advertiser_test
Content-Type: application/json

{
  "access_token": "8a697e38e16498916ba9883a2e45b3d09570e153",
  "advertiser_id" : "1832088598807818"
}

###

POST http://localhost:8002/api/jlaccount/getCountry_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468665720323"
}

###

POST http://localhost:8002/api/jlaccount/getBind_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/getAvatarUpload_test
Content-Type: application/json

{
  "access_token": "6a144cfbbac2cb1afce126ee4d8e74920cb4f279",
  "advertiser_id" : "1816784868360331"
}

###

POST http://localhost:8002/api/jlaccount/getAvatarSubmit_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1825659930906858"
}

###

POST http://localhost:8002/api/jlaccount/getAdmin_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468665720323"
}

###

POST http://localhost:8002/api/jlaccount/getAssets_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830643928627204"
}

###

POST http://localhost:8002/api/jlaccount/getAssetConfigs_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830643928627204"
}

###

POST http://localhost:8002/api/jlaccount/getMicro_game_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468454821898"
}

###


POST http://localhost:8002/api/jlaccount/getWechat_game_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/getAvailableEvents_test
Content-Type: application/json

{
  "access_token": "6d65bd9d250a89c88cd845e2e339f4c902adff41",
  "advertiser_id" : "1827737161788811"
}

###

POST http://localhost:8002/api/jlaccount/getCreateAssets_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830643928627204"
}

###

POST http://localhost:8002/api/jlaccount/getCreateEvents_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830643928627204"
}

###

POST http://localhost:8002/api/jlaccount/getCreateMicroApp_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830643839405063"
}

###

POST http://localhost:8002/api/jlaccount/getUpdateMicroApp_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830432400447060"
}

###

POST http://localhost:8002/api/jlaccount/getAssetLink_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830432400447060"
}

###

POST http://localhost:8002/api/jlaccount/shareMicroApp_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8"
}

###

POST http://localhost:8002/api/jlaccount/getShareMicroApp_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830643839405063"
}

###

POST http://localhost:8002/api/jlaccount/createPromotion_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468665720323"
}

###
POST http://localhost:8002/api/jlaccount/getUpdateAdvertiser_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468454821898"
}

###


POST http://localhost:8002/api/jlaccount/createProject_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/createDpaProduct_test
Content-Type: application/json

{
  "access_token": "e134836bf440406bffbbd67bcb942b38ded37ab8",
  "advertiser_id" : "1830432400447060"
}

###

POST http://localhost:8002/api/jlaccount/createUploadTask
Content-Type: application/json

{
  "access_token": "aa49ff7266a5848812e541d63435031fd4441251",
  "advertiser_id" : "1832088604446025"
}

###

POST http://localhost:8002/api/jlaccount/uploadTaskList
Content-Type: application/json

{
  "access_token": "aa49ff7266a5848812e541d63435031fd4441251",
  "advertiser_id" : "1832088604446025"
}

###

POST http://localhost:8002/api/pushMaterials/postToObjectName
Date: GMT Date
Content-Type: application/json

{

}

###

POST http://localhost:8002/api/material/getUrl_test
Date: GMT Date
Content-Type: application/json

{

}

###

POST http://localhost:8002/api/material/pushMaterialTest
Date: GMT Date
Content-Type: application/json

{

}

###

POST http://localhost:8002/api/jlaccount/updatePromotionStatus_test
Content-Type: application/json

{
  "access_token": "947c9e265b39950772a0c71f92d54869626abc2c",
  "advertiser_id" : "1832088604446025",
  "promotion_id" : "7509909034074751030"
}

###

POST http://localhost:8002/api/jlaccount/updatePromotion_test
Content-Type: application/json

{
  "access_token": "947c9e265b39950772a0c71f92d54869626abc2c",
  "advertiser_id" : "1832088604446025",
  "promotion_id" : "7509909034074751030"
}

###

POST http://localhost:8002/api/material/autoPromotionTest
Content-Type: application/json

{

}

###
