
POST http://localhost:8002/api/playlet/save
Content-Type: application/json

{
  "distributor_id": "1814524549803018",
  "playlet_id": "7477466360931418651"
}

###

POST http://localhost:8002/api/jlaccount/getAccessToken
Content-Type: application/json

{
  "appid": "1830365792890956",
  "authcode": "7a17267bc7a1d7f05187ae6577be5ec3001cb3ee",
  "secret": "d89f8cae68457fff4b954ffb31c633ab9b794f20"
}

###

POST http://localhost:8002/api/jlaccount/saveJlaccount
Content-Type: application/json

{
"account": "htduanju06@163.com",
"authcode": "d1cd791912df8d1b87aa20af544814afba45d5ba"
}

###

POST http://localhost:8002/api/jlaccount/refreshToken
Content-Type: application/json

{
  "appid": "1830365792890956",
  "refreshtoken": "1eeee1bfe14578f0ac4ac304f3f95e343afea3e5",
  "secret": "d89f8cae68457fff4b954ffb31c633ab9b794f20"
}

###

POST http://localhost:8002/api/jlaccount/getVideo
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829459264055556"
}

###

POST http://localhost:8002/api/jlaccount/getImage
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829455239457027"
}

###

POST http://localhost:8002/api/jlaccount/getCarousel
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468342951300"
}

###

POST http://localhost:8002/api/jlaccount/getCarouselAd
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468342951300",
  "carousel_ids" : "7494621992639266855",
  "carousel_ids1" : "7494622024477163532"
}

###

POST http://localhost:8002/api/jlaccount/getAwemeAuth
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468665720323"
}

###

POST http://localhost:8002/api/jlaccount/getPromotion
Content-Type: application/json

{
  "access_token": "7b7e5bfd54e760321aecb8b30affbc1d453c2dc5",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/video_cover
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468665720323",
  "video_id": "v03033g10000d00rtffog65h88vh0ljg"
}

###

POST http://localhost:8002/api/jlaccount/getMicroApp_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/getAvailables_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/getDpaDetail_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898",
  "product_platform_id" : "1699307224909595"
}

###

POST http://localhost:8002/api/jlaccount/getProject_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/advertiser_test
Content-Type: application/json

{
  "access_token": "42a4d401237fdbbb7b2cb8dab01252532370578f",
  "advertiser_id" : "1829456490475595"
}

###

POST http://localhost:8002/api/jlaccount/getCountry_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468665720323"
}

###

POST http://localhost:8002/api/jlaccount/getAdmin_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468665720323"
}

###

POST http://localhost:8002/api/jlaccount/getAssets_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/getMicro_game_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###


POST http://localhost:8002/api/jlaccount/getWechat_game_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###

POST http://localhost:8002/api/jlaccount/createPromotion_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468665720323"
}

###
POST http://localhost:8002/api/jlaccount/getUpdateAdvertiser_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###


POST http://localhost:8002/api/jlaccount/createProject_test
Content-Type: application/json

{
  "access_token": "dee57caef991bd8f37fc0aebb8814c01a8e15d22",
  "advertiser_id" : "1829468454821898"
}

###

